arch:
    - amd64
    - ppc64le
dist: trusty
sudo: required
language: python
cache:
    - apt
before_install:
    - sudo apt-get install -y software-properties-common
    - sudo add-apt-repository -y "deb http://us.archive.ubuntu.com/ubuntu/ trusty universe multiverse restricted"
    - sudo apt-get update -qq
    - sudo apt-get install -y opencl-headers fglrx ocl-icd-opencl-dev
env:
    - TOX_ENV=py3
    - TOX_ENV=py27
    - TOX_ENV=py27-tf
    - TOX_ENV=py3-tf
    - TOX_ENV=docs
install:
    - pip install --upgrade pip
    - pip install tox coveralls
script:
    - tox -e $TOX_ENV
after_success:
    - coveralls

